### ISSUE TITLE
pinned_hits not working on the first page and pinned items don't get removed from the search list

### ISSUE THREAD

**Issue by axionos** [typesense/typesense#156]
## Description

I'm trying to do two queries:
```
1. to get a list of Ids of data 
2. to get a list of data that has certain ones on the top by using the list from the first query as `pinned_hits` value
```
It works if the length of pinned_hits is less or equal to the per_page number of the second query, but the pinned data still remains in its original position which makes it look like the search result has duplicate data.

It doesn't work when the length of pinned_hits is bigger than the per_page number. On the first page, nothing gets pinned, but items are pinned on the second and third pages. Duplicates still remain in the search result.

## Steps to reproduce

1. Do the first query with `per_page` value 4, and the second query with `per_page` value 4 or bigger and `pinned_hits` value as the list of data Ids from the first query.

2. Do the first query with `per_page` value 250, and the second query with `per_page` value 8 and `pinned_hits` value as the list of data Ids from the first query.

## Expected Behavior

1. Do the first query with `per_page` value 4, and the second query with `per_page` value 4 or bigger and `pinned_hits` value as the list of data Ids from the first query.
-> Pinned items appear on the top of the list and get removed from the original position, so they don't repeat in the search result.

2. Do the first query with `per_page` value 250, and the second query with `per_page` value 8 and `pinned_hits` value as the list of data Ids from the first query.
-> First page should display the pinned items on the top of the list and those pinned items get removed from the original position.

## Actual Behavior

1. Do the first query with `per_page` value 4, and the second query with `per_page` value 4 or a bigger number and `pinned_hits` value as the list of data Ids from the first query.
-> Pinned items appear on the top of the list but it doesn't get removed from the original position so that there are repeated data in the search result.

2. Do the first query with `per_page` value 250, and the second query with `per_page` value 8 and `pinned_hits` value as the list of data Ids from the first query.
-> Nothing is pinned on the first page, but items are pinned on the second and third pages. Those pinned items don't get removed from the original position so they are repeated in the search result.

## Metadata

**Typsense Version**: 0.17.0.rc4

**OS**: Mac

**Comment by kishorenc** [comment]
👋 Thanks for reporting this issue. I am looking into this and as well as https://github.com/typesense/typesense/issues/154. Will update soon.

**Comment by kishorenc** [comment]
@axionos I was not able to reproduce the first issue, **but** I identified an issue that caused the second issue and fixed that. Can you try on this Docker image: `typesense/typesense:0.18.0.rc1` ?

If issue no. 1 is still happening, I need the exact query being sent so that I can dig further.

This build should also fix the issue you are facing with https://github.com/typesense/typesense/issues/154.

**Comment by hadfield** [comment]
we don't use docker.  can you provide a download?

**Comment by hadfield** [comment]
the pinned hits problem appears to occur when the number of pinned hits is greater than the page size for the first page.

**Comment by kishorenc** [comment]
> the pinned hits problem appears to occur when the number of pinned hits is greater than the page size for the first page.

Yes I think I have fixed that edge case in this build.

Downloads:

- https://dl.typesense.org/releases/0.18.0.rc1/typesense-server-0.18.0.rc1-1.x86_64.rpm
- https://dl.typesense.org/releases/0.18.0.rc1/typesense-server-0.18.0.rc1-amd64.deb
- https://dl.typesense.org/releases/0.18.0.rc1/typesense-server-0.18.0.rc1-linux-amd64.tar.gz

**Comment by axionos** [comment]
@kishorenc 
Thanks for providing me the update. I see that it fixed the issue with the first page not displaying pinned_hits. However, the duplicate data still appears in its original position.

**Comment by kishorenc** [comment]
1. Can you please give me the actual query you are making when the duplicates appear?
2. How many pinned IDs are you passing?
3. What is the number of results when the pinned IDs are not used?
4. Are you able to reproduce the issue on a small set of 5-10 records? If so, please share that so I can use that example to troubleshoot.

**Comment by hadfield** [comment]
A quick comment -- this is a case of 18 pinned hits with page size of 8, so on page 3 of the results it's the last of the pinned hits plus the first of the non-pinned hits.  the page 3 non-pinned hits include documents that were pinned hits on page 1 and 2.

**Comment by axionos** [comment]
1. 
`const pinned_list = '311:1, 284:2, 103:3, 52:4, 309:5, 287:6, 280:7, 277:8, 263:9, 216:10, 215:11, 194:12, 193:13, 174:14, 138:15, 122:16, 89:17, 12:18';`

`let searchParameters = {
          q: query.length > 0 ? query : '*',
          query_by: 'name, hasDirectoryContentHTML, hasDirectoryKeywords',
          page: pageNum,
          per_page: 8,
          sort_by: query.length > 0 ? '' : 'alphaNumericalOrder:asc',
          pinned_hits: `${pinned_list}`
        };`

2. 18 Ids
3. 
When pinned IDs are not used: 129 found, 8 returned
When pinned IDs are used: 143 found, 8 returned

**Comment by kishorenc** [comment]
Thank you, I will troubleshoot.

**Comment by kishorenc** [comment]
@axionos 

I think I've addressed this. Can you please try against `0.18.0.rc2`:

Downloads:

https://dl.typesense.org/releases/0.18.0.rc2/typesense-server-0.18.0.rc2-1.x86_64.rpm
https://dl.typesense.org/releases/0.18.0.rc2/typesense-server-0.18.0.rc2-linux-amd64.tar.gz

**Comment by axionos** [comment]
Hi @kishorenc 
I tried the 0.18.0.rc2 version and tested it, but the issue still persists. 
The pinned items are still staying at the original position instead of being removed.

**Comment by kishorenc** [comment]
Sorry to hear that the issue still persists. Is it possible for you to reproduce the issue on a small sample dataset that you can share with me along with the query either via client code or a CURL request? 

It should be simple to fix it once I can reproduce the issue with a small dataset.

**Comment by hadfield** [comment]
@kishorenc what email can i send a sample dataset to?

**Comment by kishorenc** [comment]
kishore at typesense org

**Comment by hadfield** [comment]
ok, sent you some data and the schema

**Comment by hadfield** [comment]
the problem seems to occur when the number of pinned hits is a few multiples of the page size, so that pinned hits that appear in search results on page 1 reappear as non-pinned results after the pinned hits, such as on page 3.

**Comment by hadfield** [comment]
i replied to your email, but just to track it here, the query would be a phrase like "risk" and not a wild card case.

**Comment by kishorenc** [comment]
@axionos Can you please try on: 

- https://dl.typesense.org/releases/0.18.0.rc3/typesense-server-0.18.0.rc3-1.x86_64.rpm
- https://dl.typesense.org/releases/0.18.0.rc3/typesense-server-0.18.0.rc3-linux-amd64.tar.gz

**Comment by axionos** [comment]
Hi @kishorenc 
The new update (0.18.0.rc3) seems to resolve the issue! Thank you!

**Comment by kishorenc** [comment]
🎉 Thanks for the help here.

**Comment by jasonbosco** [comment]
Just released v0.18.0 with this fix: https://github.com/typesense/typesense/releases/tag/v0.18.0.
