### ISSUE TITLE
Prefix search in filter_by not getting all the results

### ISSUE THREAD

**Issue by Gabrimarin** [typesense/typesense#1659]
## Description

I am trying to use the new prefix in filter_by added in v26, but only 4 items of my collection are showing up. I think this would be related to the max_candidates parameter,  but it seems to be exclusive to the query system. Maybe some "max_candidates" equivalent need to be added to the filter_by prefix search

## Steps to reproduce

- Get a collection with 10 items, each one with a "type" field. Each item will have a different value for "type", but they all start with the same prefix, like "test-1", "test-2", "test-3",...,"test-10"
- Try to filter_by the prefix (filter_by=type:test*)

## Expected Behavior

Should bring all the items that start with "test"

## Actual Behavior

Only 4 items that start with "test" were found

## Metadata

**Typesense Version**: 26

**Comment by marcopesani** [comment]
+1, It's really limiting the usage of prefix filtering

**Comment by alexquant1993** [comment]
I'm testing in my app as well and it doesn't work. It doesn't return the whole expected list or either returns an empty list when results are expected.

**Comment by solvingproblemswithtechnology** [comment]
I just found the same issue and it's being pretty limiting. Also, there's no easy workaround. Is it possible to have a 26.1 with this?

**Comment by jasonbosco** [comment]
We've address this in `27.0.rc20`. Could you give it a shot and let me know how it goes?

**Comment by solvingproblemswithtechnology** [comment]
I just tried, I still face the same issue with a 3M+ dataset. It doesn't reproduce on a smaller one, like 400 records.

**Comment by servehub-llc** [comment]
What is the status of this?  I'm testing out and seeing limited results returned.

I'm using this syntax for what it's worth:

/multi_search?query_by=customer_name

```
{
    "searches": [
            {
              "collection": "customers",
              "q": "*",
              "filter_by": "customer_name:=F*"             
            }
          ]
}
```

**Comment by alexquant1993** [comment]
This issue persists in version v27.1, and it’s becoming a significant roadblock as we approach our planned launch in the coming months. The lack of this functionality severely limits the effectiveness of our search feature.

Here’s an example of the problem:

When using the filter "filter_by: categoryID: 0205*", the search works as expected. However, when trying a broader search like "filter_by: categoryID: 02*", it returns an empty list. Interestingly, the filter works correctly with other categories, such as "filter_by: categoryID: 09*".

Could you please investigate this further?

**Comment by Gabrimarin** [comment]
Here on my project I'm using the `prefix` search param with a small workaround to mimic the behavior of the prefix filter.

**Comment by kishorenc** [comment]
This is fixed in `28.0.rc12`.

You can use the `max_filter_by_candidates` search parameter to increase the number of candidates looked for prefix filtering.

**Comment by aiorga-sherpas** [comment]
Prefix filtering is still failing when used to order the results of the query. A small example using the "Build A Search Application" dataset:

```
search_parameters = {
  'q'         : 'light',
  'query_by'  : 'title',
  'sort_by': '_eval([ (title:=Se*):1 ]):desc',
  'max_filter_by_candidates': 300

}
```
Results:
```
Light
Night Light: A Restoration Novel
Sea of Silver Light
Hands of Light: A Guide to Healing Through the Human Energy Field
Agents of Light and Darkness
A Certain Slant of Light
A Ring of Endless Light (Austin Family, #4)
Light A Penny Candle
QED: The Strange Theory of Light and Matter
Fifth Grave Past the Light
```

In this case Sea of Silver Light should be above the others.

**Comment by alangmartini** [comment]
Hi @aiorga-sherpas  and @Gabrimarin 

Could you check if this is working as expected in the latest v29.0.rc27?

**Comment by kishorenc** [comment]
Part of v29.0 GA release.
