### ISSUE TITLE
Get error max sort fields when using q and sort_by in joined collection

### ISSUE THREAD

**Issue by xian13** [typesense/typesense#1909]
## Description

We get an error "Only upto 3 sort_by fields can be specified." when the sort_by only have 3 fields, but one of this field is joined collection.

## Steps to reproduce

Main collection schema: 

```json
{
  "name": "product",
  "fields": [
    {"name": "id", "type": "string" },
    {"name": "name", "type": "string", "sort": true },
    {"name": "brand", "type": "string", "sort": true }
  ]
}
```

Main collection data:

```jsonl
{"id":"satu","name": "name","brand":"brand"}
{"id":"dua","name": "name","brand":"brand"}
{"id":"tiga","name": "name","brand":"brand"}
```

Joined collection schema:

```json
{
  "name": "product_price",
  "fields": [
    {"name": "id", "type": "string" },
    {"name": "product_id", "type": "string", "reference": "product.id" },
    {"name": "type_id", "type": "int32" },
    {"name": "price", "type": "int32" }
  ]
}
```

Joined collection data:

```jsonl
{"id": "satu_1","product_id":"satu","type_id":1,"price": 10000}
{"id": "dua_1","product_id":"dua","type_id":1,"price": 5000}
{"id": "tiga_1","product_id":"tiga","type_id":1,"price": 2500}
```

Query on `product`:

```json
{
  "q": "satu",
  "query_by": "name",
  "filter_by": "$product_price(type_id:=1)",
  "sort_by": "name:asc,brand:asc,$product_price(price:asc)"
}
```

## Expected Behavior

Get result and no error because sort_by only use 3 fields.

## Actual Behavior

Get error message `Only upto 3 sort_by fields can be specified.`

But if query `*`, the result is returned and no error.

```json
{
  "q": "*",
  "query_by": "name",
  "filter_by": "$product_price(type_id:=1)",
  "sort_by": "name:asc,brand:asc,$product_price(price:asc)"
}
```

## Metadata

**Typesense Version**: 26.0

**OS**: Docker with image typesense/typesense:26.0 on Macos M1

**Comment by happy-san** [comment]
Recently a similar issue was fixed. Can you try same query with `typesense:27.0.rc35` ?

**Comment by xian13** [comment]
@happy-san i just tried same query in `typesense:27.0.rc35` and the error didn't happened, so it will be solved in release 27 and release 26 will still have the issue?

**Comment by happy-san** [comment]
Yes, v26 will have this issue. Also, v27 GA build is about to be published very soon.

**Comment by xian13** [comment]
I see, ok thanks for the solution and info
