### ISSUE TITLE
symbols_to_index at field level not working correctly?

### ISSUE THREAD

**Issue by W1zzardTPU** [typesense/typesense#2351]
Schema:
`{
  "name": "test2",
  "fields": [
    {
      "name": "name",
      "type": "string",
      "facet": true,
      "optional": false,
      "index": true,
      "sort": true,
      "infix": false,
      "locale": "",
      "stem": false,
      "stem_dictionary": "",
      "store": true,
      "symbols_to_index": [
        "+"
      ]
    }
  ],
  "default_sorting_field": "",
  "enable_nested_fields": false,
  "symbols_to_index": [],
  "token_separators": [
    "-",
    "(",
    ")"
  ]
}`

Now create a document with name = "C++", then facet search for "C++" -> empty result set

If symbols_to_index at the collection level contains "+", everything will work fine.

**Comment by tharropoulos** [comment]
This was fixed in `v29.0.rc20`

**Comment by W1zzardTPU** [comment]
ooooh, thank you!

Confirmed to be working in the reduced test but not with my production data, will test more and let you know

**Comment by W1zzardTPU** [comment]
Hmm .. could you try with my test case from first post? I'm definitely running 29.0.rc20, but "C++" is still not showing up in the results.

**Comment by jackwilsdon** [comment]
Is it possible this is the same as #2828?

**Comment by tharropoulos** [comment]
@jackwilsdon No, #2828 is how Typesense tokenizes queries based on the most weighted field's tokenization rules. This includes symbols to index, locale, stemming and token separators.
