### ISSUE TITLE
Unable to filter by id

### ISSUE THREAD

**Issue by sanmoh-dojo** [typesense/typesense#395]
## Description

We recently updated to typesense/typesense:0.22.0.rcu7 and now when creating new collections it automatically pops out the id field from the collection making it unable for us to filter or search using that field

## Steps to reproduce

Create collection. Sample below
```
{
	"fields": [
		{
			"facet": true,
			"index": true,
			"name": "id",
			"optional": false,
			"type": "string"
		},
		{
			"facet": true,
			"index": true,
			"name": "org_id",
			"optional": false,
			"type": "string"
		},
		{
			"facet": true,
			"index": true,
			"name": "customer_id",
			"optional": true,
			"type": "string"
		}
	],
	"name": "test"
}
```

## Expected Behavior

Collection should be created and when we try to retrieve it this should be the response
```
{
    "created_at": 1633171210,
    "default_sorting_field": "",
    "fields": [
		{
			"facet": true,
			"index": true,
			"name": "id",
			"optional": false,
			"type": "string"
		},
		{
			"facet": true,
			"index": true,
			"name": "org_id",
			"optional": false,
			"type": "string"
		},
		{
			"facet": true,
			"index": true,
			"name": "customer_id",
			"optional": true,
			"type": "string"
		}
	],
    "name": "test",
    "num_documents": 0,
    "num_memory_shards": 4
}
```

## Actual Behavior

This is what we're getting instead
```
{
    "created_at": 1633171210,
    "default_sorting_field": "",
    "fields": [
        {
            "facet": true,
            "index": true,
            "name": "org_id",
            "optional": false,
            "type": "string"
        },
        {
            "facet": true,
            "index": true,
            "name": "customer_id",
            "optional": true,
            "type": "string"
        }
    ],
    "name": "test",
    "num_documents": 0,
    "num_memory_shards": 4
}
```

## Metadata

**Typsense Version**:

**OS**:

**Comment by kishorenc** [comment]
@sanmoh-dojo There was a regression which has since been fixed in the `0.22.0.rcs7` build. Please use that.

**Comment by sanmoh-dojo** [comment]
@kishorenc We updated to 0.22.0.rcs7 and the issue still seems to be persisting.

**Comment by kishorenc** [comment]
The `id` field will not be accepted as part of the schema but you should be able to refer to it for filtering. I just tried and it works for me on `0.22.0.rcs7`. If it is not working, please provide a set of CURL commands that I can use to reproduce the issue.

**Comment by kishorenc** [comment]
Here's the sequence that worked for me:

```
# Create a collection
curl "http://localhost:8108/collections" \
        -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: abcd" \
        -d '{
                "name": "docs",
                "fields": [
                        { "name": ".*", "type": "auto" }
                ]
        }'

# Insert a doc

curl "http://localhost:8108/collections/docs/documents?dirty_values=coerce_or_reject&action=upsert" -X POST \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{"id": "100", "points":10,"title":"Test"}'

# Filter using ID:

curl http://localhost:8108/collections/docs/documents/search?q=*&x-typesense-api-key=abcd&filter_by=id:100

```

**Comment by sanmoh-dojo** [comment]
Okay awesome. I checked and filter by id works inspite of it not showing up in the schema.

But I also noticed that query_by id doesn't work is this intentional ?

**Comment by kishorenc** [comment]
If you want to query by ID, use the `/collections/:collection/documents/:id` end-point. The `id` is a special field so it cannot be used for all operations. If you want to treat it as a proper string field, index it as regular field, something like `identifier` so you can run all operations on it.
