### ISSUE TITLE
Bug: typesense can't commit a record with empty array value

### ISSUE THREAD

**Issue by tremendus** [typesense/typesense#473]
## Description

Seems that typesense won't accept a document with an empty array as a value

## Steps to reproduce

Create schema:
```
{
    "created_at": 1640193019,
    "default_sorting_field": "",
    "fields": [
        {
            "facet": false,
            "index": true,
            "name": ".*",
            "optional": true,
            "type": "auto"
        },
        {
            "facet": false,
            "index": true,
            "name": "label",
            "optional": true,
            "type": "string"
        }
    ],
    "name": "groups",
    "num_documents": 0,
    "symbols_to_index": [],
    "token_separators": []
```

Try to index this document:
```
{
    _location: null,
    description: null,
    label: 'Kindergarten',
    type: 'grade',
    meta: { created: { at: null, by: null }, updated: { at: null, by: null } },
    _grades: [],
    _people: [],
    tenant: 'one',
    collection: 'groups',
    id: 'grade-kindergarten-all'
}
```

## Expected Behavior

The document should be commited

## Actual Behavior

JS client returns an error from database

```
RequestMalformed [Error]: Request failed with HTTP code 400 | Server said: Type of field `_grades` is invalid.
```

## Metadata

**Typsense Version**: package.json: `"typesense": "^1.0.2"`

**OS**: Node14 (Firebase function environment)

**Comment by kishorenc** [comment]
@tremendus 

Can you please test against this Docker build: `typesense/typesense:0.23.0.rc10`

It should be fixed.

**Comment by kishorenc** [comment]
Patched in `v0.22.2`.

**Comment by mokhosh** [comment]
@kishorenc Still doesn't seem to work:

```
Error importing document: Field `translations` must be an array of string.
```

Trying to add a document with `$translations = []` in Laravel, with this config:
```php
[
    'name' => 'translations',
    'type' => 'string[]',
    'optional' => true,
],
```
