### ISSUE TITLE
Typesense stops processing data and times out after creating/destroying indices in a fast interval [macOS]

### ISSUE THREAD

**Issue by pyr0hu** [typesense/typesense#678]
## Description

I have a Laravel project which uses Typesense through the official PHP package. We are using Typesense in our test suites too. To avoid having "race conditions" - meaning our tests run in parallel and we want to keep our data separate per test case - we are creating a new index for each test case and destroying it after every case. This is done using a prefix for each index. Like `users` becomes `1-ExampleTestCase-users`

This works properly on Linux developer machines with Docker. Our CI is running the tests in Docker too, flawless in there too.

But when we are running locally the test suite on Mac, Typesense just stops processing the data and times out. This is after running around 20 test cases with index creation/destruction.

After this, doing anything, including indexing new data, or modifying the collections just times out.

Pressing CTRL-C on typesense does not stop the server, but showing the message of "Shutting down..." but keeps on running. I think it stuck when stopping the batch indexer as that's the last log I can see.

After killing the process with `htop` and restarting the server, same stuff, times out. The only way we could restart properly if we delete the data directory which contained the typesense data.

If I remove the prefix and index create/destroy code, it works properly and the test suite runs on the mac computer.

## Steps to reproduce

- Start a typesense server
- Run index re-creation in fast succession

## Expected Behavior

Typesense should not get stuck

## Metadata

**Typesense Version**: 0.23.1

**OS**: macOS 12.3.1

**Comment by kishorenc** [comment]
I think this has already been fixed in a recent Mac build, can you please check against `0.24.0.rc24`? Docker image is uploaded, and the Mac build is [here](https://dl.typesense.org/releases/0.24.0.rc24/typesense-server-0.24.0.rc24-darwin-amd64.tar.gz).

**Comment by pyr0hu** [comment]
@kishorenc I've tried the rc, still happens. This is the last "stat" log that I have:

`I20220728 19:32:26.805320 153694208 raft_server.cpp:534] Term: 2, last_index index: 1263, committed_index: 1263, known_applied_index: 1263, applying_index: 0, queued_writes: 2, pending_queue_size: 0, local_sequence: 5782`

When CTRL-C-ing:

```
I20220728 19:32:29.462168 314852864 typesense_server_utils.cpp:47] Stopping Typesense server...
W20220728 19:32:29.794085 71061504 default_variables.cpp:300] Fail to sscanf: Undefined error: 0 [0]
I20220728 19:32:29.814353 153694208 typesense_server_utils.cpp:335] Typesense peering service is going to quit.
I20220728 19:32:29.814417 153694208 raft_server.cpp:774] Set shutting_down = true
I20220728 19:32:29.814427 153694208 raft_server.cpp:778] Waiting for in-flight writes to finish...
I20220728 19:32:29.814435 153694208 raft_server.cpp:784] Replication state shutdown, store sequence: 5782
I20220728 19:32:29.814445 153694208 raft_server.cpp:788] node->shutdown
I20220728 19:32:29.814457 153694208 node.cpp:929] node default_group:192.168.0.122:8107:8108 shutdown, current_term 2 state LEADER
I20220728 19:32:29.814559 153694208 replicator.cpp:1475] Group default_group Fail to find the next candidate
I20220728 19:32:29.814570 191791104 raft_server.h:287] Node stepped down : Raft node is going to quit.
I20220728 19:32:29.814620 191791104 raft_server.h:291] This node is down
I20220728 19:32:29.814623 153694208 raft_server.cpp:792] node->join
I20220728 19:32:29.814651 153694208 node.cpp:929] node default_group:192.168.0.122:8107:8108 shutdown, current_term 2 state SHUTDOWN
I20220728 19:32:29.814855 153694208 typesense_server_utils.cpp:340] raft_server.stop()
I20220728 19:32:29.814882 153694208 server.cpp:1100] Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is going to quit
I20220728 19:32:29.815145 153694208 typesense_server_utils.cpp:343] raft_server.join()
I20220728 19:32:29.815223 153694208 typesense_server_utils.cpp:346] Typesense peering service has quit.
I20220728 19:32:29.815919 153694208 typesense_server_utils.cpp:469] Shutting down batch indexer...
I20220728 19:32:29.815963 153694208 typesense_server_utils.cpp:472] Waiting for batch indexing thread to be done...
I20220728 19:32:30.796869 154230784 batched_indexer.cpp:282] Notifying batch indexer threads about shutdown...
I20220728 19:32:30.797083 154230784 batched_indexer.cpp:290] Batched indexer threadpool shutdown...
```

**Comment by kishorenc** [comment]
Can you please share a script that I can run that reproduces the problem?

**Comment by kishorenc** [comment]
This has been fixed in 0.24.0
