### ISSUE TITLE
When typesense crash and restart it destroy its own database

### ISSUE THREAD

**Issue by irevoire** [typesense/typesense#769]
## Description

Hello, while trying to help on https://github.com/typesense/typesense/issues/768 I found a strange bug.
If typesense gets ctrl+c ed and then rerun it corrupt itself and after a few ctrl+c + restart it simply can't start at all.

## Steps to reproduce

1. On one term: `./typesense-server -d data.sense -a a`
2. On another terminal: Create a books collection: `curl "http://localhost:8108/collections" \\
        -X POST \\
        -H "X-TYPESENSE-API-KEY: a" \\
        -d '{\
              "name": "books",\
              "fields": [\
                {"name": "title", "type": "string" },\
                {"name": "author", "type": "string" },\
                {"name": "ratings", "type": "int32" }\
              ],\
              "default_sorting_field": "ratings"\
            }'`
3. Upload three documents in it: `curl "http://localhost:8108/collections/books/documents/import" \\
        -X POST \\
        -H "X-TYPESENSE-API-KEY: a" \\
        -d '\
          {"title":"Book 1","author":"Author1","ratings":24}\
          {"title":"Book 2","author":"Author2","ratings":31}\
          {"title":"Book 3","author":"Author3","ratings":30}'`
4. Create another `movies` collection: `curl "http://localhost:8108/collections" \\
        -X POST \\
        -H "X-TYPESENSE-API-KEY: a" \\
        -d '{\
              "name": "movies",\
              "fields": [\
                {"name": "title", "type": "string" },\
                {"name": "poster", "type": "string" }\
              ]\
            }'`
5. Push documents in it: `curl "http://localhost:8108/collections/movies/documents/import" \\
        -X POST \\
        -H "X-TYPESENSE-API-KEY: a" \\
        -d '\
          {"title":"Spiderman","poster":"A cool pic"}\
          {"title":"SuperMan","poster":"superhero", "hello": "test"}'`
6. Get back on the first terminal and kill typesense.
7. Rerun typesense and do a search: `curl "http://localhost:8108/collections/movies/documents/search?query_by=title&q="
        -H "X-TYPESENSE-API-KEY: a" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   378    0   378    0     0  64187      0 --:--:-- --:--:-- --:--:--  369k
{
  "facet_counts": [],
  "found": 2,
  "hits": [
    {
      "document": {
        "author": "Author2",
        "id": "1",
        "ratings": 31,
        "title": "Book 2"
      },
      "highlights": [],
      "text_match": 100
    },
    {
      "document": {
        "author": "Author1",
        "id": "0",
        "ratings": 24,
        "title": "Book 1"
      },
      "highlights": [],
      "text_match": 100
    }
  ],
  "out_of": 2,
  "page": 1,
  "request_params": {
    "collection_name": "movies",
    "per_page": 10,
    "q": ""
  },
  "search_cutoff": false,
  "search_time_ms": 0
}`
8. As you can see I got books in my `movies` collection 😭 
9. After a bunch of restarts typesense simply stopped starting
10. And when looking at my rocksdb databases I simply couldn't retrieve anything, it looks like the document disappeared from the db?

## Expected Behavior

It works.

## Actual Behavior

It doesn't works.

## Metadata

**Typsense Version**: [0.23.1](https://github.com/typesense/typesense/releases/tag/v0.23.1)

**OS**: macOS

**Comment by irevoire** [comment]
It's quite a big issue for me. If I want to run it in prod I would certainly put my typesense server in a systemctl file and make it restart in case a crash occurs.
Same with k8s / docker, but it looks like typesense will simply kill itself after a few restarts 🥺

**Comment by kishorenc** [comment]
I was unable to reproduce the issue you faced. I extracted those commands onto a bash script that you can run: https://gist.github.com/kishorenc/97e9b86dbd04738b4fefa426a598a87b

If you can share a similar script that showcases the issue, I will be happy to look into it.

**Comment by kishorenc** [comment]
@irevoire 

However, this sounds like an issue that I addressed a couple of months earlier which involved a race condition during multiple collection creation. If you use Docker, can you try reproducing it on the nightly? 

```
docker push typesense/typesense:0.24.0.rcn25
```

**Comment by irevoire** [comment]
@kishorenc I can't test it right now, but from what I see in your script you forgot to kill and restart typesense right?
It's what corrupt the database

**Comment by kishorenc** [comment]
Ah, got it. I'm able to reproduce now on Mac on 0.23.1 but not on latest nightly. It must be the same issue that I fixed. Feel free to use the Docker nightly build above. Next version of Typesense (0.24) will be out in a few weeks and will contain this patch.

**Comment by irevoire** [comment]
Ah, nice! Feel free to close when you want then 😁
