### ISSUE TITLE
Setting null inside a nested multiple object errors unexpectly expected array of string

### ISSUE THREAD

**Issue by alexander-schranz** [typesense/typesense#874]
## Description

When try to add a json document which has object[] in it which is nested runs into an unexpected error for `null` values.

## Steps to reproduce

Document:

```json
{
    "uuid": "23b30f01-d8fd-4dca-b36a-4710e360a965",
    "title": null,
    "header": {
        "image": {
            "media": 1
        }
    },
    "article": "<article><h2>New Subtitle<\/h2><p>A html field with some content<\/p><\/article>",
    "blocks": {
        "text": [
            {
                "_originalIndex": 0,
                "title": "Titel",
                "description": "<p>Description<\/p>",
                "media": [
                    3,
                    4
                ]
            },
            {
                "_originalIndex": 1,
                "title": "Titel 2",
                "description": null
            },
            {
                "_originalIndex": 3,
                "title": "Titel 4",
                "description": "<p>Description 4<\/p>",
                "media": [
                    3,
                    4
                ]
            }
        ],
        "embed": [
            {
                "_originalIndex": 2,
                "title": "Video",
                "media": "https:\/\/www.youtube.com\/watch?v=iYM2zFP3Zn0"
            }
        ]
    },
    "footer": {
        "title": null
    },
    "created": 1643022000,
    "commentsCount": 2,
    "rating": 3.5,
    "comments": [
        {
            "email": "admin.nonesearchablefield@localhost",
            "text": "Awesome blog!"
        },
        {
            "email": "example.nonesearchablefield@localhost",
            "text": "Like this blog!"
        }
    ],
    "tags": [
        "Tech",
        "UI"
    ],
    "categoryIds": [
        1,
        2
    ],
    "id": "23b30f01-d8fd-4dca-b36a-4710e360a965"
}
```

Schema:

```json
[
    {
        "name": "uuid",
        "type": "string",
        "facet": true
    },
    {
        "name": "title",
        "type": "string",
        "optional": true,
        "index": true
    },
    {
        "name": "header",
        "type": "object",
        "optional": true
    },
    {
        "name": "header.image",
        "type": "object",
        "optional": true
    },
    {
        "name": "header.image.media",
        "type": "int64",
        "optional": true,
        "index": false
    },
    {
        "name": "header.video",
        "type": "object",
        "optional": true
    },
    {
        "name": "header.video.media",
        "type": "string",
        "optional": true,
        "index": false
    },
    {
        "name": "article",
        "type": "string",
        "optional": true,
        "index": true
    },
    {
        "name": "blocks",
        "type": "object",
        "optional": true
    },
    {
        "name": "blocks.text",
        "type": "object[]",
        "optional": true
    },
    {
        "name": "blocks.text._originalIndex",
        "type": "int64[]",
        "optional": true
    },
    {
        "name": "blocks.text.title",
        "type": "string[]",
        "optional": true,
        "index": true
    },
    {
        "name": "blocks.text.description",
        "type": "string[]",
        "optional": true,
        "index": true
    },
    {
        "name": "blocks.text.media",
        "type": "int64[]",
        "optional": true,
        "index": false
    },
    {
        "name": "blocks.embed",
        "type": "object[]",
        "optional": true
    },
    {
        "name": "blocks.embed._originalIndex",
        "type": "int64[]",
        "optional": true
    },
    {
        "name": "blocks.embed.title",
        "type": "string[]",
        "optional": true,
        "index": true
    },
    {
        "name": "blocks.embed.media",
        "type": "string[]",
        "optional": true,
        "index": false
    },
    {
        "name": "footer",
        "type": "object",
        "optional": true
    },
    {
        "name": "footer.title",
        "type": "string",
        "optional": true,
        "index": true
    },
    {
        "name": "created",
        "type": "int64",
        "optional": true,
        "index": true
    },
    {
        "name": "commentsCount",
        "type": "int64",
        "optional": true,
        "index": false
    },
    {
        "name": "rating",
        "type": "float",
        "optional": true,
        "index": false
    },
    {
        "name": "comments",
        "type": "object[]",
        "optional": true
    },
    {
        "name": "comments.email",
        "type": "string[]",
        "optional": true,
        "index": false
    },
    {
        "name": "comments.text",
        "type": "string[]",
        "optional": true,
        "index": true
    },
    {
        "name": "tags",
        "type": "string[]",
        "optional": true,
        "index": true
    },
    {
        "name": "categoryIds",
        "type": "int64[]",
        "optional": true,
        "index": false
    }
]
```

## Expected Behavior

No error should be shown for `null` values inside a nest object.

## Actual Behavior

```bash
1) Schranz\Search\SEAL\Adapter\Typesense\Tests\TypesenseAdapterTest::testDocument
Typesense\Exceptions\RequestMalformed: Field `blocks.text.description` must be an array of string.
```

## Metadata

**Typesense Version**:

**OS**: MacOS X
**Docker** typesense/typesense 0.24.0

**Comment by kishorenc** [comment]
@alexander-schranz 

Fixed in this Docker build: `typesense/typesense:0.24.1.rc4`

**Comment by alexander-schranz** [comment]
Tested `typesense/typesense:0.24.1.rc11` and still getting the same error there.

```
1) Schranz\Search\SEAL\Adapter\Typesense\Tests\TypesenseAdapterTest::testDocument
Typesense\Exceptions\RequestMalformed: Field `blocks.text.description` must be an array of string.
```

**Comment by huntjosh** [comment]
Running into this issue as well on v0.25.1

**Comment by alexander-schranz** [comment]
Seems not longer be the case in `26.0`
